---
title: "Selection on organ-biased genes (*`r params$species.name`*)"
author: "Bucao, Christabel Floi"
output: html_document
date: "`r Sys.Date()`"
params:
  input.selection.rds.path: "../../results/08_Selection"
  input.tau.rds.path: "../../results/10_Expression_Specificity"
  output.rds.path: "../../results/11_Selection_Organ_Bias"
  species: "DRE"
  species.name: "Danio rerio"
  tau.cutoff: 0.30
  qc1.only: FALSE
  combat: FALSE
---

# Setup {.tabset}

## Parameters
```{r print-params}
print(params)
```

## Libraries
```{r import-libraries}
library(dplyr)
library(ggplot2)
library(ggpubr)
```

## Functions
```{r source-functions}
source("../functions/selection.R")
source("../functions/selection_plots.R")
```

## Data

### Filtered selection data
```{r import-filtered-selection-data}
if (!params$combat) {
  if (!params$qc1.only) {
    input.selection.path <- file.path(params$input.selection.rds.path, "no_combat", "full_qc")    
  } else {
    input.selection.path <- file.path(params$input.selection.rds.path, "no_combat", "qc1_only")        
  }

} else {
  if (!params$qc1.only) {
    input.selection.path <- file.path(params$input.selection.rds.path, "combat", "full_qc")    
  } else {
    input.selection.path <- file.path(params$input.selection.rds.path, "combat", "qc1_only")        
  }

}

# Load saved data from 08_Selection.Rmd
## Filtered Selectome results
selectome.sub <- readRDS(
  file.path(input.selection.path,
            paste(params$species, "selectome.sub.rds", sep="_")))

### With median variability across conditions
#### Background gene set
selectome.bgd.groupby.gene.ev.median <- readRDS(
  file.path(input.selection.path,
            paste(params$species, "selectome.bgd.groupby.gene.ev.median.rds", sep="_")))  

```

### Expression specificity (tau)
```{r import-tau}
if (!params$combat) {
  if (!params$qc1.only) {
    input.tau.path <- file.path(params$input.tau.rds.path, "no_combat", "full_qc")    
  } else {
    input.tau.path <- file.path(params$input.tau.rds.path, "no_combat", "qc1_only")        
  }
} else {
  if (!params$qc1.only) {
    input.tau.path <- file.path(params$input.tau.rds.path, "combat", "full_qc")    
  } else {
    input.tau.path <- file.path(params$input.tau.rds.path, "combat", "qc1_only")     
  }
}

# Load expression specificity computations from 10_Expression_Specificity.Rmd
## Conditions available in all species
filtered.samples <- readRDS(
  file.path(input.tau.path,
            paste(params$species, "filtered.samples.common.rds", sep="_")))   
 
```

# Main {.tabset}

## Bind selection - expression specificity - primary organ
```{r bind-selection-tau-organ-bias}
selection.tau.tissue <- selectome.sub$Bgd %>%
  dplyr::inner_join(filtered.samples$expr.rank.first, by="GeneID")

selection.tau.tissue$TissueBias <-
  apply(selection.tau.tissue, MARGIN=1, function(r) {
    if (r[["tau"]] <= params$tau.cutoff) { "broad" }
    else { r[["PrimaryTissue"]] }
  })

# Only organ-biased genes
selection.tau.tissue.biased <- selection.tau.tissue %>%
  dplyr::filter(tau > params$tau.cutoff)

# Group by GeneID
## The estimated omega0 is the same across all branches of each gene tree
## Add median variability rank across conditions
selection.tau.tissue.groupby.gene <- selection.tau.tissue %>%
  dplyr::group_by(GeneID, PrimaryTissue, tau, TissueBias) %>%
  dplyr::summarise(
    omega0 = mean(omega0)
  ) %>%
  dplyr::ungroup() %>%
  dplyr::inner_join(selectome.bgd.groupby.gene.ev.median, by=c("GeneID","omega0"))

# Broadly expressed genes
selection.tau.tissue.groupby.gene.broad <- selection.tau.tissue.groupby.gene %>%
  dplyr::filter(TissueBias=="broad") %>%
  check_missing_bins(all.bins=seq(0.1,1,0.1)) # Add any missing bins for visualization

# Organ-biased genes
selection.tau.tissue.groupby.gene.biased <- selection.tau.tissue.groupby.gene %>%
  dplyr::filter(TissueBias!="broad") %>%
  check_missing_bins(all.bins=seq(0.1,1,0.1))
```

## Strength of purifying selection

### Boxplot - omega0 grouped by organ bias
```{r boxplot-omega0-organ-bias, fig.width=10, fig.height=8}
comparisons <- list(c("brain","broad"))

ggplot(selection.tau.tissue, 
       aes(x=reorder(TissueBias, omega0, FUN=median, na.rm=TRUE), 
           y=omega0)) +
  stat_boxplot(geom='errorbar') +
  geom_boxplot(notch=TRUE) +
  ylim(c(-0.01,0.50)) +
      stat_summary(fun.data=annotate_n, geom="text", fun=median, 
                   position= position_dodge(width = 0.75), size=5) +      
      stat_summary(fun.data=annotate_median, geom="text", fun=median, 
                   position=position_dodge(width = 0.75), size=5) +
  stat_compare_means(aes(label=..p.signif..),
                     test="wilcox.test",
                     comparisons=comparisons,
                     label.y=0.40, size=7) +
  labs(title=params$species.name,
       x="Organ bias", y="ω0 (dN/dS < 1)") +
  theme_bw() +
  theme(plot.title=element_text(size=20, face="italic"),
        axis.title=element_text(size=18),
        axis.text=element_text(size=14))

ggplot(selection.tau.tissue.groupby.gene, 
       aes(x=reorder(TissueBias, omega0, FUN=median, na.rm=TRUE), 
           y=omega0)) +
  stat_boxplot(geom='errorbar') +
  geom_boxplot(notch=TRUE) +
  ylim(c(-0.01,0.50)) +
      stat_summary(fun.data=annotate_n, geom="text", fun=median, 
                   position= position_dodge(width = 0.75), size=5) +      
      stat_summary(fun.data=annotate_median, geom="text", fun=median, 
                   position=position_dodge(width = 0.75), size=5) +
  stat_compare_means(aes(label=..p.signif..),
                     test="wilcox.test",
                     comparisons=comparisons,
                     label.y=0.40, size=7) +
  labs(title=params$species.name,
       x="Organ bias", y="ω0 (dN/dS < 1)") +
  theme_bw() +
  theme(plot.title=element_text(size=20, face="italic"),
        axis.title=element_text(size=18),
        axis.text=element_text(size=14))
```


### Boxplots - omega0 grouped by variability rank

#### Broadly expressed genes
```{r boxplot-omega0-varbins-broad, fig.width=10, fig.height=8}
boxplot_omega0_varbins(selection.tau.tissue.groupby.gene.broad, compare.extremes=TRUE, title=params$species.name)
```

#### Organ-biased genes
```{r boxplot-omega0-varbins-biased, fig.width=10, fig.height=8}
try(boxplot_omega0_varbins(selection.tau.tissue.groupby.gene.biased, compare.extremes=TRUE, title=params$species.name))
```


# Save
```{r save-objects}
if (!params$combat) {
  if (!params$qc1.only) {
      output.path <- file.path(params$output.rds.path, "no_combat", "full_qc")
  } else {
      output.path <- file.path(params$output.rds.path, "no_combat", "qc1_only")    
  }
} else {
  if (!params$qc1.only) {
    output.path <- file.path(params$output.rds.path, "combat", "full_qc")    
  } else {
    output.path <- file.path(params$output.rds.path, "combat", "qc1_only")        
  }

}

if (!dir.exists(output.path)) { dir.create(output.path, recursive=TRUE, showWarnings=FALSE) }

saveRDS(selection.tau.tissue,
        file.path(output.path, 
                  paste(params$species, 
                        paste("selection", paste0("tau", params$tau.cutoff),
                              "tissue", "rds", sep="."), sep="_")))

saveRDS(selection.tau.tissue.biased,
        file.path(output.path, 
                  paste(params$species, 
                        paste("selection", paste0("tau", params$tau.cutoff),
                              "tissue.biased", "rds", sep="."), sep="_")))

saveRDS(selection.tau.tissue.groupby.gene,
        file.path(output.path, 
                  paste(params$species, 
                        paste("selection", paste0("tau", params$tau.cutoff),
                              "tissue.groupby.gene", "rds", sep="."), sep="_")))  

```

